#!/usr/bin/env bash
set -euo pipefail

OUTFILE="backend/.env"
FORCE=0
SUBSCRIPTION=""

usage() {
  cat <<'USAGE'
Usage: fetch-cosmos-conn.sh -n <cosmosAccountName> -g <resourceGroup> [-o <outFile>] [-s <subscriptionId>] [-f]

Fetch the Cosmos DB (Mongo API) primary connection string and write it to a .env file
that can be used by the backend (default: backend/.env).

Options:
  -n <name>         Cosmos DB account name (required)
  -g <rg>           Resource group name (required)
  -o <outFile>      Output file (default: backend/.env)
  -s <subscription> Azure subscription id or name (optional)
  -f                Force overwrite of the output file if it exists
  -h                Show this help

Example:
  ./scripts/fetch-cosmos-conn.sh -n my-cosmos -g rg-todoapp-dev -o backend/.env
USAGE
}

while getopts ":n:g:o:s:fh" opt; do
  case ${opt} in
    n) ACCOUNT=${OPTARG} ;; 
    g) RG=${OPTARG} ;; 
    o) OUTFILE=${OPTARG} ;; 
    s) SUBSCRIPTION=${OPTARG} ;; 
    f) FORCE=1 ;; 
    h) usage; exit 0 ;; 
    :) echo "Option -${OPTARG} requires an argument."; usage; exit 1 ;; 
    \?) echo "Invalid option: -${OPTARG}"; usage; exit 1 ;;
  esac
done

if [ -z "${ACCOUNT:-}" ] || [ -z "${RG:-}" ]; then
  echo "Error: -n <cosmosAccountName> and -g <resourceGroup> are required." >&2
  usage
  exit 2
fi

if ! command -v az >/dev/null 2>&1; then
  echo "Azure CLI (az) is not installed or not in PATH. Install/ login and retry." >&2
  exit 3
fi

AZ_EXTRA_ARGS=()
if [ -n "$SUBSCRIPTION" ]; then
  AZ_EXTRA_ARGS+=(--subscription "$SUBSCRIPTION")
fi

echo "Fetching Cosmos DB connection string for account '$ACCOUNT' in resource group '$RG'..."
set +e
CONN=$(az cosmosdb keys list --name "$ACCOUNT" --resource-group "$RG" --type connection-strings "${AZ_EXTRA_ARGS[@]}" --query "connectionStrings[0].connectionString" -o tsv 2>/dev/null)
AZ_EXIT=$?
set -e

if [ $AZ_EXIT -ne 0 ] || [ -z "$CONN" ] || [ "$CONN" = "None" ]; then
  echo "Failed to fetch connection string via 'az cosmosdb keys list --type connection-strings'." >&2
  echo "Try running 'az cosmosdb keys list --name $ACCOUNT --resource-group $RG --type connection-strings' manually to inspect output." >&2
  exit 4
fi

echo "Connection string fetched successfully."

if [ -f "$OUTFILE" ] && [ $FORCE -ne 1 ]; then
  echo "Output file '$OUTFILE' already exists. Use -f to overwrite." >&2
  exit 5
fi

mkdir -p "$(dirname "$OUTFILE")"
cat > "$OUTFILE" <<EOF
# Generated by scripts/fetch-cosmos-conn.sh
COSMOS_MONGO_CONN="$CONN"
EOF

chmod 600 "$OUTFILE" || true
echo "Wrote connection string to $OUTFILE (permissions set to 600)."
echo "IMPORTANT: Do not commit $OUTFILE to git. Add it to .gitignore if needed."
